services:
    _defaults:
        autowire: true
        public: false
        autoconfigure: true

    Lle\HermesBundle\:
        resource: '../../../src/*'
        exclude: '../../../src/{DependencyInjection,Entity,Resources,Enum,LleHermesBundle.php}'

    Lle\HermesBundle\Service\SenderService:
        arguments:
            - '@mailer.mailer'
            - '@doctrine.orm.entity_manager'
            - '@Lle\HermesBundle\Repository\RecipientRepository'
            - '@Lle\HermesBundle\Repository\UnsubscribeEmailRepository'
            - '@Lle\HermesBundle\Service\MailBuilderService'
