services:
    _defaults:
        autowire: true
        public: false
        autoconfigure: true

    Lle\HermesBundle\:
        resource: '../../../src/*'
        exclude: '../../../src/{DependencyInjection,Entity,Resources,Enum,LleHermesBundle.php}'

    Lle\HermesBundle\Service\Sender:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Lle\HermesBundle\Repository\EmailErrorRepository'
            - '@mailer.mailer'
            - '@Lle\HermesBundle\Service\MailBuilder'
            - '@parameter_bag'
            - '@Lle\HermesBundle\Repository\RecipientRepository'
            - '@Lle\HermesBundle\Repository\UnsubscribeEmailRepository'

    Lle\HermesBundle\Service\MailError\MailRecoverer:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@Lle\HermesBundle\Service\MailError\MailAnalyzer'
            - '@parameter_bag'
