services:
    _defaults:
        autowire: true
        public: false
        autoconfigure: true

    Lle\HermesBundle\:
        resource: '../../../src/*'
        exclude: '../../../src/{DependencyInjection,Entity,Resources,Enum,LleHermesBundle.php}'
